In [4]:
import datetime
from datetime import datetime, date
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
pd.set_option('display.notebook_repr_html',True)
pd.set_option('display.max_columns',7)
pd.set_option('display.max_rows',10)
pd.set_option('display.width',250)
%matplotlib inline
from re import match
import os
import json

In [9]:
## 패키지 import
import pymysql

## 버전확인
# print(pymysql.version_info)

## DB연동을 위한 설정 정보
config = {     # DB연동을 위한 환경변수
    'host':'127.0.0.1', # 각자의 접속DB주소, 127.0.0.1
    'user':'scott',
    'password':'tiger',
    'database':'work',
    'port':3306,
    'charset':'utf8',
    'use_unicode':True
}

try:
    # DB연동 객체 생성
    # 1. 직접 객체 정보를 입력
    # conn = pymysql.connect(host='127.0.0.1',user='scott',password='tiger',database='work',port=3306,charset='utf8',use_unicode=True)
    # 2. 사전 설정된 정보를 적용
    conn = pymysql.connect(**config)    # 딕셔너리형태의 인자를 넘길 때 **를 사용
    # sql문 실행 객체 : cursor
    cursor = conn.cursor()
    # 테이블 조회
    sql = 'show tables'
    cursor.execute(sql)
    tables = cursor.fetchall()           # 리스트로 반환
    # 테이블 유무 확인
    if tables:
        print('테이블이 존재합니다\n',tables)
    else:
        print('테이블이 존재하지 않습니다')
        
except Exception as e:
    print('DB연동 에러발생',e)
    conn.rollback()     # insert, update, delete
finally:
    cursor.close()
    conn.close()

테이블이 존재합니다
 (('goods',),)

In [21]:
## Mysql CRUD 동작
# 1. 기존의 goods 테이블을 삭제
# 2. 파이썬 코드를 이용하여 DB와 연결객체를 생성
# 3. DB안에 goods테이블을 생성
# 4. 생성된 goods테이블에 레코드 추가 작성
#    작성시 input을 이용하여 code,name,su,dan을 입력받아서 레코드 추가
#    conn.commit => DB적용
# 5. 전체 목록보기(전체 목록을 출력한 후에 전체 목록 개수도 출력)
# 6. 상품명 조회 (상품명을 입력받아 해당 상품명에 따른 레코드를 출력)

config = {     # DB연동을 위한 환경변수
    'host':'127.0.0.1', # 각자의 접속DB주소, 127.0.0.1
    'user':'scott',
    'password':'tiger',
    'database':'work',
    'port':3306,
    'charset':'utf8',
    'use_unicode':True
}

try:
    conn = pymysql.connect(**config)
    cursor = conn.cursor()
    
    # 기존 테이블 삭제
    # sql1 = 'drop table goods'
    # cursor.execute(sql1)
    
    # 테이블 재생성
    sql2 = 'CREATE TABLE if not exists goods(CODE INT PRIMARY KEY,NAME VARCHAR(30) NOT NULL,su INT default 0,dan INT default 0);'
    cursor.execute(sql2)
    conn.commit()

    while True: 
        sel = input('레코드를 추가하시겠습니까? (Y/n)')
        if sel != 'n':        
            # 레코드 추가
            code = int(input('코드를 입력하세요 : '))
            name = input('상품명을 입력하세요 : ')
            su = int(input('수량을 입력하세요 : '))
            dan = int(input('단가를 입력하세요 : '))
            sql3 = f"insert into goods values({code},'{name}',{su},{dan})"
            cursor.execute(sql3)
            conn.commit()
        else:
            break
    
    # 전체 목록 보기
    sql4 = "select * from goods"
    cursor.execute(sql4)
    lst = cursor.fetchall()
    for row in lst:    
        print("%d   %s  %d  %d"%row)
    
    # 목록 개수 출력
    print("검색 레코드수 : ",len(lst))
    
    # 상품조회
    name_s = input('\n찾을 상품명을 입력하세요 : ')
    sql6 = f"select * from goods where name like '%{name_s}%'"
    cursor.execute(sql6)
    search = cursor.fetchall()
    if search:
        print('검색한 상품이름 : ',name_s)
        for fow in search:
            print(row[0],row[1],row[2],row[3])
    else:
        print('해당 상품이 존재하지 않습니다.')
    
except Exception as e:
    print('DB연동 실패',e)
    conn.rollback()
    
finally:
    cursor.close()
    conn.close()

1   냉장고  2  850000
2   세탁기  3  550000
3   전자레인지  2  350000
4   HDTV  3  1500000
검색 레코드수 :  4
검색한 상품이름 :  T
4 HDTV 3 1500000

In [ ]:
### 위 문제를 이용하여 다음과 같은 메뉴로 동작하는 DB프로그램 작성
# -----메뉴-----
# 1. 상품등록
# 2. 상품조회(전체)
# 3. 상품조회(이름으로 조회)
# 4. 상품수정(코드로)
# 5. 상품삭제(코드로)
# 0. 종료
# 조건
# 1. 각 기능을 함수로 구현하세요
# 2. 반복기능을 사용하여 구현하세요

config = {     # DB연동을 위한 환경변수
    'host':'127.0.0.1', # 각자의 접속DB주소, 127.0.0.1
    'user':'scott',
    'password':'tiger',
    'database':'work',
    'port':3306,
    'charset':'utf8',
    'use_unicode':True
}

def selectAll():
    sql = "select * from goods"
    cursor.execute(sql)
    lst = cursor.fetchall()
    return lst
 
def selectOne(name):
    sql = f"select * from goods where name like '%{name}%'"
    cursor.execute(sql)
    search = cursor.fetchall()
    return search

def insert(code,name,su,dan):
    
    sql = f"insert into goods values({code},'{name}',{su},{dan})"
    cursor.execute(sql)
    conn.commit()
    
def update(code):
    name = input('수정할 상품명을 입력하세요 : ')
    su = int(input('수정할 수량을 입력하세요 : '))
    dan = int(input('수정할 단가를 입력하세요 : '))
    sql = f"update goods set name={name},su={su},dan={dan} where code={code}"
    cursor.execute(sql)
    conn.commit()
    
def delete(code):
    sql = f"delete from goods where code={code}"
    cursor.execute(sql)
    
try:
    while True:
        conn = pymysql.connect(**config)
        cursor = conn.cursor() 
        print('-'*5+'메뉴'+'-'*5+'\n1. 상품등록\n2. 상품조회(전체)\n3. 상품조회(상품명검색)\n4. 상품수정\n5. 상품삭제\n0.프로그램 종료')
        sel = int(input('메뉴를 선택하세요'))
        if sel == 0:
            print('프로그램을 종료합니다.')
            break
        elif sel == 1:
            # 레코드 추가
            code = int(input('코드를 입력하세요 : '))
            name = input('상품명을 입력하세요 : ')
            su = int(input('수량을 입력하세요 : '))
            dan = int(input('단가를 입력하세요 : '))
            insert(code,name,su,dan)
        elif sel == 2:        
            # 전체 목록 보기
            selectAll()
            for row in lst:    
                print("%d   %s  %d  %d"%row)
            # 목록 개수 출력
            print("검색 레코드수 : ",len(lst))
        elif sel == 3:
            # 상품조회
            name_s = input('\n찾을 상품명을 입력하세요 : ')
            selectOne(name_s)
            if search:
                print('검색한 상품이름 : ',name_s)
                for fow in search:
                    print(row[0],row[1],row[2],row[3])
            else:
                print('해당 상품이 존재하지 않습니다.')
        elif sel == 4:
            code = int(input('수정할 상품코드를 입력하세요 : '))
            update(code)
            print('수정이 완료되었습니다.')
            selectAll()
        elif sel == 5:
            code = int(input('삭제할 상품코드를 입력하세요 : '))
            delete(code)
        else:
            print('메뉴를 잘못선택하셨습니다. 다시 입력해주세요.')
            continue
except Exception as e:
    print('DB연동 실패',e)
    conn.rollback()
    
finally:
    cursor.close()
    conn.close()

In [ ]:
def CreateTable():
    try:
        conn = pymysql.connect(**config)
        cursor = conn.cursor()
    
        # 테이블 재생성
        sql = 'CREATE TABLE if not exists goods(CODE INT PRIMARY KEY,NAME VARCHAR(30) NOT NULL,su INT default 0,dan INT default 0);'
        cursor.execute(sql)
        conn.commit()
    except Exception as e:
        print('테이블 생성 에러발생',e)
    finally:
        cursor.close()
        conn.close()
    
def insert(code,name,su,dan):
    try:
        conn = pymysql.connect(**config)
        cursor = conn.cursor()
        sql = f"insert into goods values({code},'{name}',{su},{dan})"
        cursor.execute(sql)
        conn.commit()
    except Exception as e:
        print('입력실패',e)
        conn.rollback()
    finally:
        cursor.close()
        conn.close()
        
def SelectAll():
    try:
        conn = pymysql.connect(**config)
        cursor = conn.cursor()
        sql = sql = "select * from goods"
        cursor.execute(sql)
        lst = cursor.fetchall()
        print("code\tname\t수량\t단가")
        for row in lst:
            print("{}\t{}\t{}\t{}".format(row[0],row[1],row[2],row[3]))
        print('총 상품 수량 : ',len(lst))
    except Exception as e:
        print('전체 조회 실패',e)
        
    finally:
        cursor.close()
        conn.close()
        
def SelectOne(name):
    try:
        conn = pymysql.connect(**config)
        cursor = conn.cursor()
        sql = f"select * from goods where name like '%{name}%'"
        cursor.execute(sql)
        rows = cursor.fetchall()
        if rows:
            print("code\tname\t수량\t단가")
            for row in rows:
                print("{}\t{}\t{}\t{}".format(row[0],row[1],row[2],row[3])) 
        else:
            print('해당 상품이 없습니다.')
    except Exception as e:
        print('개별 조회 실패',e)
    finally: 
        cursor.close()
        conn.close()

def update(code):
    try:
        conn = pymysql.connect(**config)
        cursor = conn.cursor()
        name = input('수정할 상품명을 입력하세요 : ')
        su = int(input('수정할 수량을 입력하세요 : '))
        dan = int(input('수정할 단가를 입력하세요 : '))
        sql = f"update goods set name={name},su={su},dan={dan} where code={code}"
        cursor.execute(sql)
        conn.commit()
    except Exception as e:
        print('수정 실패',e)
    finally:
        cursor.close()
        conn.close()
        
def delete(code):
    try:
        conn = pymysql.connect(**config)
        cursor = conn.cursor()
        sql = f"delete from goods where code={code}"
        del_sel = input('정말 삭제하시겠습니까? (Y/n) : ')
        if del_sel.lower() == 'y':
            cursor.execute(sql)
            conn.commit()
        else:
            print('삭제를 취소합니다.')
    except Exception as e:
        print('삭제 실패',e)
    finally:
        cursor.close()
        conn.close()
        
while True:
    os.system('cls')
    print('-----메뉴-----'+'\n1. 상품등록\n2. 상품조회(전체)\n3. 상품조회(상품명검색)\n4. 상품수정\n5. 상품삭제\n0.프로그램 종료')
    
    CreateTable()
    
    sel = int(input('메뉴를 선택하세요'))
    
    match sel:
        case '1':
            code = int(input('코드를 입력하세요 : '))
            name = input('상품명을 입력하세요 : ')
            su = int(input('수량을 입력하세요 : '))
            dan = int(input('단가를 입력하세요 : '))
            insert(code,name,su,dan)
        case '2':
            print('전체상품조회')
            selectAll()
        case '3':
            print('개별상품조회')
            name = input('\n찾을 상품명을 입력하세요 : ')
            selectOne(name)
        case '4':
            print('상품 정보 수정')
            code = int(input('수정할 상품의 코드를 입력하세요 : '))
            update(code)
        case '5':
            print('상품 정보 삭제')
            code = int(input('삭제할 상품의 코드를 입력하세요 : '))
            update(code)
        case '0':
            print('프로그램을 종료합니다.')
            os.system('pause')
            break
        case _:
            print('메뉴 선택을 잘못했습니다.')
            os.system('pause')

In [ ]:
### 앞서 만들어진 함수를 Class로 구성하세요
## -----메뉴-----
# 1. 상품등록
# 2. 상품조회(전체)
# 3. 상품조회(상품명 또는 코드)
#       - 상품명 : 상품명으로 조회
#       - 코드 입력시 : code를 사용하여 조회
# 4. 상품수정(코드로)
# 5. 상품삭제(코드로)
# 0. 종료
# 
# 조건 : 전체 기능을 하나의 클래스에서 구현

In [4]:
import pymysql
config = {     # DB연동을 위한 환경변수
    'host':'127.0.0.1', # 각자의 접속DB주소, 127.0.0.1
    'user':'scott',
    'password':'tiger',
    'database':'work',
    'port':3306,
    'charset':'utf8',
    'use_unicode':True
}

class Product:
    def __init__(self,config):
        self.config = config
        self.conn = pymysql.connect(**self.config)
        self.cursor = self.conn.cursor()
        #print('객체 생성 확인 : ',self.conn)
        #print('커서 객체 확인 : ',self.cursor)
        
    def createTable(self):
        sql = 'CREATE TABLE if not exists goods(CODE INT PRIMARY KEY,NAME VARCHAR(30) NOT NULL,su INT default 0,dan INT default 0);'
        self.cursor.execute(sql)
        self.conn.commit()
    
    def insert(self,code,name,su,dan):
        sql = f"insert into goods values({code},'{name}',{su},{dan})"
        self.cursor.execute(sql)
        self.conn.commit()    
    
    def selectAll(self):    
        sql = sql = "select * from goods"
        self.cursor.execute(sql)
        lst = self.cursor.fetchall()
        print("code\tname\t\t수량\t단가")
        for row in lst:
            print("{}\t{}\t\t{}\t{}".format(row[0],row[1],row[2],row[3]))
        print('총 상품 수량 : ',len(lst))
    
    def selectOne_n(self,name):
        sql = f"select * from goods where name like '%{name}%'"
        self.cursor.execute(sql)
        rows = self.cursor.fetchall()
        if rows:
            print("code\tname\t\t수량\t단가")
            for row in rows:
                print("{}\t{}\t\t{}\t{}".format(row[0],row[1],row[2],row[3])) 
        else:
            print('해당 상품이 없습니다.')

    def selectOne_c(self,code):
        sql = f"select * from goods where code like '%{code}%'"
        self.cursor.execute(sql)
        rows = self.cursor.fetchall()
        if rows:
            print("code\tname\t\t수량\t단가")
            for row in rows:
                print("{}\t{}\t\t{}\t{}".format(row[0],row[1],row[2],row[3])) 
        else:
            print('해당 상품이 없습니다.')
    
    def update(self,code):
        name = input('변경할 상품명을 입력하세요 : ')
        su = int(input('변경할 수량을 입력하세요 : '))
        dan = int(input('변경할 단가를 입력하세요 : '))
        sql = f"update goods set name={name},su={su},dan={dan} where code={code}"
        self.cursor.execute(sql)
        self.conn.commit()
        
    def delete(self,code):
        sql = f"delete from goods where code={code}"
        del_sel = input('정말 삭제하시겠습니까? (Y/n) : ')
        if del_sel.lower() == 'y':
            self.cursor.execute(sql)
            self.conn.commit()
        else:
            print('삭제를 취소합니다.')


while True:
    x = Product(config)
    os.system('cls')
    print('-----메뉴-----'+'\n1. 상품등록\n2. 상품조회(전체)\n3. 상품조회(상품명검색)\n4. 상품수정\n5. 상품삭제\n0.프로그램 종료')
    
    x.createTable()
    
    sel = int(input('메뉴를 선택하세요'))
    
    match sel:
        case 1:
            code = int(input('코드를 입력하세요 : '))
            name = input('상품명을 입력하세요 : ')
            su = int(input('수량을 입력하세요 : '))
            dan = int(input('단가를 입력하세요 : '))
            x.insert(code,name,su,dan)
        case 2:
            print('전체상품조회')
            x.selectAll()
        case 3:
            print('개별상품조회')
            name = input('\n찾을 상품명을 입력하세요 : ')
            x.selectOne(name)
        case 4:
            print('상품 정보 수정')
            code = int(input('수정할 상품의 코드를 입력하세요 : '))
            x.update(code)
        case 5:
            print('상품 정보 삭제')
            code = int(input('삭제할 상품의 코드를 입력하세요 : '))
            x.delete(code)
        case 0:
            print('프로그램을 종료합니다.')
            break
        case _:
            print('메뉴 선택을 잘못했습니다.')
            os.system('pause')

-----메뉴-----
1. 상품등록
2. 상품조회(전체)
3. 상품조회(상품명검색)
4. 상품수정
5. 상품삭제
0.프로그램 종료
전체상품조회
code	name		수량	단가
1	냉장고		2	850000
2	세탁기		3	550000
3	전자레인지		2	350000
4	HDTV		3	1500000
5	컴퓨터		3	1500000
6	키보드		10	20000
7	마우스		5	8000
총 상품 수량 :  7
-----메뉴-----
1. 상품등록
2. 상품조회(전체)
3. 상품조회(상품명검색)
4. 상품수정
5. 상품삭제
0.프로그램 종료
상품 정보 삭제
-----메뉴-----
1. 상품등록
2. 상품조회(전체)
3. 상품조회(상품명검색)
4. 상품수정
5. 상품삭제
0.프로그램 종료
전체상품조회
code	name		수량	단가
1	냉장고		2	850000
2	세탁기		3	550000
3	전자레인지		2	350000
4	HDTV		3	1500000
5	컴퓨터		3	1500000
6	키보드		10	20000
총 상품 수량 :  6
-----메뉴-----
1. 상품등록
2. 상품조회(전체)
3. 상품조회(상품명검색)
4. 상품수정
5. 상품삭제
0.프로그램 종료
프로그램을 종료합니다.